export const manualRecords = [
  {
    id: "MANUAL-THAISE-20260306",
    chargeType: "Cobrança de Inscrição / Matrícula",
    method: "PIX",
    donor: "THAISE ALMEIDA",
    campaign: "",
    dueDate: "06/03/2026",
    receivedAt: "",
    creditedAt: "",
    expectedCreditAt: "",
    receivable: 702,
    paid: 0,
    credited: 0,
    fee: 0,
    installment: "1/1",
    costCenter: "",
    event: "Curso de Libras - 2026",
    acquisition: "",
    sponsorship: "",
  },
  {
    id: "MANUAL-YASMINE-20260321",
    chargeType: "Cobrança de Inscrição / Matrícula",
    method: "PIX",
    donor: "Yasmine Delefrati",
    campaign: "",
    dueDate: "21/03/2026",
    receivedAt: "",
    creditedAt: "",
    expectedCreditAt: "",
    receivable: 297,
    paid: 0,
    credited: 0,
    fee: 0,
    installment: "1/1",
    costCenter: "",
    event: "Curso de Libras - 2026",
    acquisition: "",
    sponsorship: "",
  },
];

export const excludedParticipants = [
  "LUCIANA CAROLINE CORREIA DA SILVA",
  "JAQUELINE PEREIRA FACHONE",
];
